initial update

diff --git a/bin/check-elf-dynamic-objects b/bin/check-elf-dynamic-objects
--- a/bin/check-elf-dynamic-objects
+++ b/bin/check-elf-dynamic-objects
@@ -15,6 +15,24 @@ set -euo pipefail
 PARA=1
 check_path="${INSTDIR:-.}"
 
+help()
+{
+    cat << "EOF"
+    -d <dir>  directory to check
+    -p        run unbound parallel checks
+    -h        help
+EOF
+    [ -z "${1:-}" ] && exit 0
+}
+
+die()
+{
+    echo "$1"
+    echo
+    help 1
+    exit 1
+}
+
 while [ "${1:-}" != "" ]; do
     parm=${1%%=*}
     arg=${1#*=}
@@ -28,12 +46,18 @@ while [ "${1:-}" != "" ]; do
     case "${parm}" in
         --dir|-d)
 	    if [ "$has_arg" ] ; then
-		check_path=$arg
+		check_path="$arg"
 	    else
 		shift
-		check_path=$1
+		check_path="$1"
 	    fi
-            ;;
+	    if [ ! -d "$check_path" ]; then
+		die "Invalid directory '$check_path'"
+	    fi
+	    ;;
+        -h)
+	    help
+	    ;;
         -p)
 	    # this sound counter intuitive. but the idea
             # is to possibly support -p <n>
@@ -62,7 +86,9 @@ programfiles=$(echo ${files} | grep -o '/program/[^/]* ' | xargs -n 1 basename)
 
 # whitelists should contain only system libraries that have a good reputation
 # of maintaining ABI stability
-globalwhitelist="ld-linux-x86-64.so.2 ld-linux.so.2 libc.so.6 libm.so.6 libdl.so.2 libpthread.so.0 librt.so.1 libutil.so.1 libnsl.so.1 libcrypt.so.1 libgcc_s.so.1 libstdc++.so.6 libz.so.1 libfontconfig.so.1 libfreetype.so.6 libxml2.so.2 libxslt.so.1 libexslt.so.0"
+# allow extending the whitelist using the environment variable to be able to work
+# on the installer stuff without the need for a baseline setup
+globalwhitelist="ld-linux-x86-64.so.2 ld-linux.so.2 libc.so.6 libm.so.6 libdl.so.2 libpthread.so.0 librt.so.1 libutil.so.1 libnsl.so.1 libcrypt.so.1 libgcc_s.so.1 libstdc++.so.6 libz.so.1 libfontconfig.so.1 libfreetype.so.6 libxml2.so.2 libxslt.so.1 libexslt.so.0 ${LO_ELFCHECK_WHITELIST-}"
 x11whitelist="libX11.so.6 libXext.so.6 libSM.so.6 libICE.so.6 libXinerama.so.1 libXrender.so.1 libXrandr.so.2 libcairo.so.2"
 openglwhitelist="libGL.so.1"
 giowhitelist="libgio-2.0.so.0 libgobject-2.0.so.0 libgmodule-2.0.so.0 libgthread-2.0.so.0 libglib-2.0.so.0 libdbus-glib-1.so.2 libdbus-1.so.3"
@@ -103,6 +129,11 @@ local file="$1"
         */libvclplug_kde4lo.so|*/libkde4be1lo.so)
             whitelist="${whitelist} ${x11whitelist} ${kde4whitelist}"
         ;;
+        */libvclplug_kde5lo.so|*/libkde5be1lo.so)
+            if [ "$ENABLE_KDE5" = TRUE ]; then
+                whitelist="${whitelist} ${qt5whitelist} ${kf5whitelist} libxcb.so.1"
+            fi
+        ;;
         */libvclplug_gtklo.so|*/libqstart_gtklo.so|*/updater)
             whitelist="${whitelist} ${x11whitelist} ${gtk2whitelist}"
         ;;
@@ -116,7 +147,7 @@ local file="$1"
         ;;
         */libvclplug_gtk3_kde5lo.so)
             if [ "$ENABLE_GTK3_KDE5" = TRUE ]; then
-                whitelist="${whitelist} ${x11whitelist} ${gtk3whitelist}"
+                whitelist="${whitelist} ${x11whitelist} ${gtk3whitelist} ${qt5whitelist} ${kf5whitelist} libxcb.so.1"
             fi
         ;;
         */lo_kde5filepicker)
@@ -128,7 +159,7 @@ local file="$1"
         */libdesktop_detectorlo.so|*/ui-previewer|*/oosplash|*/gengal.bin)
             whitelist="${whitelist} ${x11whitelist}"
         ;;
-        */libvclplug_genlo.so|*/libchartcorelo.so|*/libavmediaogl.so|*/libOGLTranslo.so|*/liboglcanvaslo.so|*/libchartopengllo.so)
+        */libvclplug_genlo.so|*/libchartcorelo.so|*/libavmediaogl.so|*/libOGLTranslo.so|*/liboglcanvaslo.so)
             whitelist="${whitelist} ${x11whitelist} ${openglwhitelist}"
         ;;
         */libvcllo.so)
